version: '3.8'

services:
  diambra:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.diambra/roms:/app/roms
      - .:/app
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    depends_on:
      - ollama
    command: ["make", "local"]

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: >
      sh -c "
      ollama serve &
      sleep 10 &&
      ollama run mistral
      "

volumes:
  ollama:
